// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityFeedEntry = { id: string, project_id: string, project_name: string, user_id: string, user_name: string, activity_type: string, content: string, created_at: string, };