// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionItem = { id: string, project_id: string, project_name: string, item_type: string, message: string, severity: string, created_at: string, };