// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AITaskSuggestion } from "./AITaskSuggestion";

export type AIPhaseSuggestion = { name: string, tasks: Array<AITaskSuggestion>, };