// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditLogResponse = { id: string, project_id: string, user_id: string, user_name: string, action: string, old_value: string | null, new_value: string | null, created_at: string, };