// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BvaProjectSummary = { project_id: string, project_name: string, budget_allocated: number, budget_spent: number, variance: number, utilization_percentage: number, };