// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfirmUploadRequest = { task_id: string, file_id: string, web_url: string, };