// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountryResponse = { id: string, name: string, currency_code: string, administrative_boundaries: any, };