// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectFocusArea } from "./ProjectFocusArea";

export type CreateProjectRequest = { name: string, description: string | null, budget_allocated: number, funding_sources: Array<string>, focus_area: ProjectFocusArea, location_metadata: any, };