// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTaskRequest = { project_id: string, phase_id: string | null, name: string, start_date: string, end_date: string, };