// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionItem } from "./ActionItem";
import type { ActivityFeedEntry } from "./ActivityFeedEntry";
import type { GlobalMetrics } from "./GlobalMetrics";
import type { ProjectResponse } from "./ProjectResponse";

export type DashboardSummary = { global_metrics: GlobalMetrics, recent_projects: Array<ProjectResponse>, action_items: Array<ActionItem>, activity_feed: Array<ActivityFeedEntry>, };