// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldLogResponse = { id: string, project_id: string, author_id: string, content: string, is_edited: boolean, created_at: string, updated_at: string, };