// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalMetrics = { active_projects_count: bigint, total_budget_allocated: number, total_budget_spent: number, average_progress_percentage: number, };