// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImpactMetricSummary = { project_name: string, metric_code: string, metric_name: string, target_value: number, current_value: number, unit: string, progress_percentage: number, };