// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectStatsResponse = { project_id: string, wells_completed: bigint, active_teams: bigint, budget_spent_percent: number, };