// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectImpactMetricResponse = { id: string, project_id: string, metric_template_id: string, target_value: number, current_value: number, is_manual_override: boolean, created_at: string, updated_at: string, code: string, display_name: string, unit: string, };