// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectMediaResponse = { id: string, task_id: string, task_name: string, gdrive_file_id: string | null, gdrive_web_url: string | null, uploaded_by: string, uploaded_by_name: string, created_at: string, };