// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BvaProjectSummary } from "./BvaProjectSummary";
import type { ImpactMetricSummary } from "./ImpactMetricSummary";

export type ReportSummaryResponse = { bva_summary: Array<BvaProjectSummary>, impact_summary: Array<ImpactMetricSummary>, };