// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncTaskUpdate } from "./SyncTaskUpdate";

export type SyncTableChanges = { created: any[], updated: Array<SyncTaskUpdate>, deleted: Array<string>, };