// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export type TaskResponse = { id: string, project_id: string, phase_id: string | null, name: string, status: TaskStatus, };