// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebhookDeliveryQueueItem = { id: string, payload: any, retry_count: number, next_attempt_at: string, status: string, };